package com.tcs.destination.enums;

public enum JobStep 
{
 USER_PROCESSING,CONNECT_PROCESSING, PREPROCESS, END, PARTNER_PROCESSING,BEACON_PROCESSING,OPPORTUNITY_PROCESSING, REVENUE_PROCESSING, CUSTOMER_PROCESSING, CUSTOMER_DWLD_PROCESSING, USER_DWLD_PROCESSING, USER_DWLD_PREPROCESS, REVENUE_DWLD_PROCESSING, OPPORTUNITY_DWLD_PROCESSING, CONNECT_DWLD_PROCESSING, CONNECT_DOWNLOAD_PREPROCESS, PARTNER_DWLD_PROCESSING, 
 BEACON_DWLD_PROCESSING,CUSTOMER_CONTACT_DWLD_PROCESSING, CUSTOMER_CONTACT_PROCESSING
}
