package com.tcs.destination.enums;

public enum JobStep {
	
	CONNECT_PROCESSING, PREPROCESS, END,PARTNER_PROCESSING,OPPORTUNITY_PROCESSING, 
	REVENUE_PROCESSING,CUSTOMER_PROCESSING, CUSTOMER_DWLD_PROCESSING,USER_DWLD_PROCESSING

}
