package com.tcs.destination.enums;

public enum RequestType {
	
	USER_UPLOAD(1),
	CUSTOMER_UPLOAD(2),
	CONNECT_UPLOAD(3),
	OPPORTUNITY_UPLOAD(4),
	ACTUAL_REVENUE_UPLOAD(5),
	CUSTOMER_CONTACT_UPLOAD(6),
	PARTNER_UPLOAD(7),
	PARTNER_CONTACT_UPLOAD(8),
	BEACON_UPLOAD(9),
	USER_DOWNLOAD(10),
	CUSTOMER_DOWNLOAD(11),
	CONNECT_DOWNLOAD(12),
	OPPORTUNITY_DOWNLOAD(13),
	ACTUAL_REVENUE_DOWNLOAD(14),
	CUSTOMER_CONTACT_DOWNLOAD(15),
	PARTNER_DOWNLOAD(16),
	PARTNER_CONTACT_DOWNLOAD(17),
	BEACON_DOWNLOAD(18),
	OPPORTUNITY_DAILY_DOWNLOAD(19);
	
	private final int type;

	private RequestType(int type) {
		this.type = type;
	}
	
	public int getType() {
		return this.type;
	}

}
