package com.tcs.destination.utils;

import java.util.Arrays;
import java.util.List;


public class ReportConstants {

	public static final String IOU = "iou";
	public static final String GEOGRAPHY = "geography";
	public static final String SUBSP = "subSp";
	public static final String COUNTRY = "country";
	public static final String OFFERING = "offering";
	public static final String CATEGORY = "connectCategory";
	public static final String STARTDATE = "startDateOfConnect";
	public static final String ENDDATE = "endDateOfConnect";
	public static final String PRIMARYOWNER = "primaryOwner";
	public static final String SECONDARYOWNER = "secondaryOwner";
	public static final String CUSTOMERORPARTNERNAME = "customerOrPartnerName";
	public static final String TCSACCOUNTCONTACT = "tcsAccountContact";
	public static final String CUSTOMERCONTACTNAME = "custContactName";
	public static final String LINKOPPORTUNITY = "linkOpportunity";
	public static final String OPPORTUNITYDESCRIPTION = "opportunityDescription";
	public static final String REQUESTRECEIVEDDATE = "requestReceivedDate";
	public static final String OPPORTUNITYOWNER = "opportunityOwner";
	public static final String NEWLOGO = "newLogo";
	public static final String COMPETITORS = "competitors";
	public static final String PARTNERSHIPSINVOLVED = "partnershipsInvolved";
	public static final String DEALTYPE = "dealType";
	public static final String SALESSUPPORTOWNER = "salesSupportOwner";
	public static final String DEALREMARKSNOTES = "dealRemarksNotes";
	public static final String DEALCLOSUREDATE = "dealClosureDate";
	public static final String FACTORSFORWINLOSS = "factorsForWinLoss";
	public static final String DESCRIPTIONFORWINLOSS = "descriptionForWinLoss";
	public static final String OPPORTUNITYLINKID = "oppLinkId";
	public static final String BIDID = "bidId";
	public static final String BIDREQUESTTYPE = "bidRequestType";
	public static final String BIDREQUESTRECEIVEDDATE = "bidRequestReceiveDate";
	public static final String BIDOFFICEGROUPOWNER = "bidOfficeGroupOwner";
	public static final String TARGETBIDSUBMISSIONDATE = "targetBidSubmissionDate";
	public static final String ACTUALBIDSUBMISSIONDATE = "actualBidSubmissionDate";
	public static final String EXPECTEDDATEOFOUTCOME = "expectedDateOfOutcome";
	public static final String WINPROBABILITY = "winProbability";
	public static final String COREATTRIBUTESUSEDFORWINNING = "coreAttributesUsedForWinning";
	public static final String CONNECTNOTES = "connectNotes";
	public static final String TASK = "task";
	public static final String TASKNOTES = "taskNotes";
	public static final String TASKCOUNT = "Task Count";
	public static final String TASKID = "Task Id";
	public static final String TASKDESCRIPTION = "Task Description";
	public static final String ENTITYREFERENCE = "Entity Reference";
	public static final String TASKOWNER = "Task Owner";
	public static final String TARGETDATEFORCOMPLETION = "Target Date For Completion";
	public static final String TASKSTATUS = "Task Status";
	public static final String TASKNOTE = "Task Notes";
	public static final String TASKUPDATEDNOTES = "Task Updated Notes";
	public static final String REPORTHEADER = "reportHeader";
	public static final String REPORTHEADER1 = "reportHeader1";
	public static final String DATAROW = "dataRow";
	public static final String SERVICELINESPLIT = "Service Line Split";
	public static final String GEOSPLIT = "GEO Split";
	public static final String IOUSPLIT = "IOU Split";
	public static final String CONNECTID = "Connect Id";
	public static final String DISPLAYGEO = "Display Geography";
	public static final String DISPLAYSERVICELINE = "Display Service Line";
	public static final String DISPLAYIOU = "Display Iou";
	public static final String CONNECTNAME = "Connect Name";
	public static final String GROUPCUSTOMERNAME = "Group Customer Name";
	public static final String ROWLABEL = "Row Label";
	public static final String COUNTOFCONNECTIDS = "Count Of ConnectIds";
	public static final String CUSTOMERNAME = "Customer Name";
	public static final String OPPORTUNITYID = "OpportunityId";
	public static final String SALESSTAGE = "Sales Stage";
	public static final String OPPORTUNITYNAME = "Opportunity Name";
	public static final String DIGITALDEALVALUE = "Digital Deal Value";
	public static final String CRMID = "CrmId";
	public static final String REPORTHEADINGSTYLE = "reportHeadingStyle";
	public static final String SUBHEADINGSTYLE = "subHeadingStyle";
	public static final String SUBHEADINGSTYLE2 = "subHeadingStyle2";
	public static final String SUBHEADINGSTYLE3 = "subHeadingStyle3";
	public static final String HEADINGROW = "headingRow";
	public static final String SUBHEADER = "subHeading";
	public static final String ROWSTYLE1 = "rowStyle1";
	public static final String BOTTOMROW = "bottomStyle";
	
	public static final String BDM = "BDM";
	public static final String BDMSUPERVISOR = "BDM Supervisor";
	public static final String GEOHEAD = "GEO Heads";
	public static final String IOUHEAD = "IOU Heads";
	
	public static final String TOP30REVENUE ="Top 30 Revenue (Master Customer)";
	public static final String SUMOFTARGETREVENUES = "Sum of Target revenue FY'";
	public static final String SUMOFACHIEVEDREVENUE = "Sum of Achieved revenue FY'";
	public static final String PERCENTACHIEVED = "% Achieved";
	public static final String PERCENTACHIEVEDBRACKET = "% Achieved Bracket";
	public static final String INR = "INR";
	public static final String USD = "USD";
	public static final String COUNT = "Count";
	public static final String NOPENETRATION = "No penetration";
	public static final String ONETOTENPERCENT = "1-10% achieved";
	public static final String ELEVENTOTWENTYFIVEPERCENT = "11- 25% achieved";
	public static final String TWENTYSIXTOFIFTYPERCENT = "26- 50% achieved";
	public static final String FIFTYONETOSEVENTYFIVEPERCENT = "51- 75% achieved";
	public static final String SEVENTYSIXTOHUNDREDPERCENT = "76- 100% achieved";
	public static final String HUNDREDPERCENT = "100% achieved";
	public static final String TOTALRESULT = "Total Result";
	public static final String OVERALL = "Over all";
	public static final String PERCENTAGAINSTTOTAL = "% against Total";
	public static final String TOTALACHIEVED = "Total Achieved";
	public static final String TOTALTARGET = "Total Target";
	public static final String OVERALLSUMMARY = "Over all Summary";
	public static final String GRANDTOTAL = "Grand Total";
	public static final String SUMMARY = "Summary";
	public static final String GEO = "Geography";
	public static final String Iou = "Iou";
	public static final String BEACONTARGET = " Beacon Target";
	public static final String Q1FY = "Q1 FY'";
	public static final String Q2FY = "Q2 FY'";
	public static final String Q3FY = "Q3 FY'";
	public static final String Q4FY = "Q4 FY'";
	public static final String ACTUAL = " Actual";
	public static final String PROJECTED = " Projected";
	public static final String YTDFY = "YTD FY'";
	public static final String REVENUEQ1FY = " Revenue = Q1 FY'";
	public static final String REVENUEQ2FY = " Revenue = Q2 FY'";
	public static final String REVENUEQ3FY = " Revenue = Q3 FY'";
	public static final String REVENUEQ4FY = " Revenue = Q4 FY'";
	public static final String ACTUALQ1FY = " Actual + Q1 FY'";
	public static final String ACTUALQ2FY = " Actual + Q2 FY'";
	public static final String ACTUALQ3FY = " Actual + Q3 FY'";
	public static final String ACTUALQ4FY = " Actual + Q4 FY'";
	public static final String REVENUE = " Revenue";
	public static final String TARGETACHIEVEDPERCENT = " Target Achieved (%)";
	public static final String Q1 = "Q1";
	public static final String Q2 = "Q2";
	public static final String Q3 = "Q3";
	public static final String Q4 = "Q4";
	
	public static final String HEADER = "header";
	public static final String HEADER1 = "header1";
	public static final String ROWS = "Row";
	public static final String DIGITALDEALVALUEPROJECTCURRENCY = "projectDealValue";
	public static final String CUSTNAME = "customerName";
	public static final String WINS = "Wins";
	public static final String LOSSES = "Losses";
	public static final String PROSPECTS = "Prospects";
	public static final String PIPELINE = "Pipeline";
	public static final String OPPORTUNITIES = "Opportunities";
	public static final String TITLE = "Title";
	public static final String COMPLETEDATA = "Complete Data";
	public static final int OFFSETCOLUMNVALUE=0;
	public static final int OFFSETCOLUMNGEO=4;
	public static final int OFFSETCOLUMNIOU=8;
	public static final String STARTINGCOLUMN = "startingColumn";
	public static final String ENDINGCOLUMN = "endingColumn";
	public static final String ENDINGROW = "endingRow";
	public static final String QUARTERS[] = { "Q1", "Q2", "Q3", "Q4", "Total" };
	public static final List<String> FIRSTQUARTER = Arrays.asList("Q1 ", "APR", "JUL", "OCT","JAN");
	public static final List<String> SECONDQUARTER = Arrays.asList("Q2 ", "MAY", "AUG", "NOV","FEB");
	public static final List<String> THIRDQUARTER = Arrays.asList("Q3 ", "JUN", "SEP", "DEC","MAR");
	public static final String SUMMARYGEOGRAPHYQUERYMETHOD = "findSummaryGeography";
	public static final String HEADINGSTYLE = "headingStyle";	
	

}